CREATE DATABASE IF NOT EXISTS employee;
USE employee;

CREATE TABLE IF NOT EXISTS Data_science_team (
    EMP_ID INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENDER VARCHAR(10),
    ROLE VARCHAR(100),
    DEPT VARCHAR(100),
    EXP INT,
    COUNTRY VARCHAR(100),
    CONTINENT VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS emp_record_table (
    EMP_ID INT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    GENDER VARCHAR(10),
    ROLE VARCHAR(100),
    DEPT VARCHAR(100),
    EXP INT,
    COUNTRY VARCHAR(100),
    CONTINENT VARCHAR(100),
    SALARY VARCHAR(100),
    EMP_RATING VARCHAR(100),
    MANAGER_ID VARCHAR(100),
    PROJ_ID VARCHAR(100)
    );
    
    CREATE TABLE IF NOT EXISTS PROJ_TABLE (
    PROJECT_ID INT,
    PROJ_NAME VARCHAR(255),
    DOMAIN VARCHAR(100),
    START_DATE VARCHAR(100),
    CLOSURE_DATE VARCHAR(100),
    DEV_QTR INT,
    STATUS_ VARCHAR(100)
    );
    
LOAD DATA INFILE 'C:\\Users\\rajan sir\\Desktop\\SQL Project 1\\data_science_team.csv'
INTO TABLE Data_science_team
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE 'C:\\Users\\rajan sir\\Desktop\\SQL Project 1\\proj_table.csv'
INTO TABLE Proj_table
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; 

LOAD DATA INFILE 'C:\\Users\\rajan sir\\Desktop\\SQL Project 1\\emp_record_table.csv'
INTO TABLE emp_record_table
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

